[2024-09-28T13:34:29.609+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: DD.convertCSVtoJSON manual__2024-09-28T13:34:12.257463+00:00 [queued]>
[2024-09-28T13:34:29.620+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: DD.convertCSVtoJSON manual__2024-09-28T13:34:12.257463+00:00 [queued]>
[2024-09-28T13:34:29.620+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-28T13:34:29.620+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-09-28T13:34:29.621+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-28T13:34:29.646+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): convertCSVtoJSON> on 2024-09-28 13:34:12.257463+00:00
[2024-09-28T13:34:29.652+0000] {standard_task_runner.py:55} INFO - Started process 2366 to run task
[2024-09-28T13:34:29.654+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'DD', 'convertCSVtoJSON', 'manual__2024-09-28T13:34:12.257463+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/1.py', '--cfg-path', '/tmp/tmp7_2inp2h']
[2024-09-28T13:34:29.656+0000] {standard_task_runner.py:83} INFO - Job 138: Subtask convertCSVtoJSON
[2024-09-28T13:34:29.722+0000] {task_command.py:389} INFO - Running <TaskInstance: DD.convertCSVtoJSON manual__2024-09-28T13:34:12.257463+00:00 [running]> on host a613a4933f38
[2024-09-28T13:34:29.906+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=paulcrickard
AIRFLOW_CTX_DAG_ID=DD
AIRFLOW_CTX_TASK_ID=convertCSVtoJSON
AIRFLOW_CTX_EXECUTION_DATE=2024-09-28T13:34:12.257463+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-28T13:34:12.257463+00:00
[2024-09-28T13:34:29.907+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/1.py", line 10, in CSVTOJson
    df=pd.read_csv('data.CSV')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'data.CSV'
[2024-09-28T13:34:29.917+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=DD, task_id=convertCSVtoJSON, execution_date=20240928T133412, start_date=20240928T133429, end_date=20240928T133429
[2024-09-28T13:34:29.939+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 138 for task convertCSVtoJSON ([Errno 2] No such file or directory: 'data.CSV'; 2366)
[2024-09-28T13:34:29.948+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-28T13:34:29.964+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
