[2024-09-28T13:39:35.240+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: DD.convertCSVtoJSON manual__2024-09-28T13:34:12.257463+00:00 [queued]>
[2024-09-28T13:39:35.254+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: DD.convertCSVtoJSON manual__2024-09-28T13:34:12.257463+00:00 [queued]>
[2024-09-28T13:39:35.255+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-28T13:39:35.255+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2024-09-28T13:39:35.255+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-28T13:39:35.287+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): convertCSVtoJSON> on 2024-09-28 13:34:12.257463+00:00
[2024-09-28T13:39:35.291+0000] {standard_task_runner.py:55} INFO - Started process 2765 to run task
[2024-09-28T13:39:35.294+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'DD', 'convertCSVtoJSON', 'manual__2024-09-28T13:34:12.257463+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/1.py', '--cfg-path', '/tmp/tmpqtvyueyg']
[2024-09-28T13:39:35.296+0000] {standard_task_runner.py:83} INFO - Job 167: Subtask convertCSVtoJSON
[2024-09-28T13:39:35.395+0000] {task_command.py:389} INFO - Running <TaskInstance: DD.convertCSVtoJSON manual__2024-09-28T13:34:12.257463+00:00 [running]> on host a613a4933f38
[2024-09-28T13:39:35.826+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=paulcrickard
AIRFLOW_CTX_DAG_ID=DD
AIRFLOW_CTX_TASK_ID=convertCSVtoJSON
AIRFLOW_CTX_EXECUTION_DATE=2024-09-28T13:34:12.257463+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-28T13:34:12.257463+00:00
[2024-09-28T13:39:35.828+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/1.py", line 10, in CSVTOJson
    df = pd.read_csv('data.CSV')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'data.CSV'
[2024-09-28T13:39:35.850+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=DD, task_id=convertCSVtoJSON, execution_date=20240928T133412, start_date=20240928T133935, end_date=20240928T133935
[2024-09-28T13:39:35.932+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 167 for task convertCSVtoJSON ([Errno 2] No such file or directory: 'data.CSV'; 2765)
[2024-09-28T13:39:35.950+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-28T13:39:36.000+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
