[2024-09-28T13:40:02.746+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: DD.convertCSVtoJSON scheduled__2020-03-18T00:15:00+00:00 [queued]>
[2024-09-28T13:40:02.757+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: DD.convertCSVtoJSON scheduled__2020-03-18T00:15:00+00:00 [queued]>
[2024-09-28T13:40:02.758+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-28T13:40:02.758+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2024-09-28T13:40:02.758+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-28T13:40:02.785+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): convertCSVtoJSON> on 2020-03-18 00:15:00+00:00
[2024-09-28T13:40:02.790+0000] {standard_task_runner.py:55} INFO - Started process 2863 to run task
[2024-09-28T13:40:02.795+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'DD', 'convertCSVtoJSON', 'scheduled__2020-03-18T00:15:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/1.py', '--cfg-path', '/tmp/tmp4t8rjtpt']
[2024-09-28T13:40:02.796+0000] {standard_task_runner.py:83} INFO - Job 175: Subtask convertCSVtoJSON
[2024-09-28T13:40:02.955+0000] {task_command.py:389} INFO - Running <TaskInstance: DD.convertCSVtoJSON scheduled__2020-03-18T00:15:00+00:00 [running]> on host a613a4933f38
[2024-09-28T13:40:03.071+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=paulcrickard
AIRFLOW_CTX_DAG_ID=DD
AIRFLOW_CTX_TASK_ID=convertCSVtoJSON
AIRFLOW_CTX_EXECUTION_DATE=2020-03-18T00:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-18T00:15:00+00:00
[2024-09-28T13:40:03.073+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/1.py", line 10, in CSVTOJson
    df = pd.read_csv('data.CSV')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'data.CSV'
[2024-09-28T13:40:03.083+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=DD, task_id=convertCSVtoJSON, execution_date=20200318T001500, start_date=20240928T134002, end_date=20240928T134003
[2024-09-28T13:40:03.106+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 175 for task convertCSVtoJSON ([Errno 2] No such file or directory: 'data.CSV'; 2863)
[2024-09-28T13:40:03.128+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-28T13:40:03.151+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
