[2024-09-28T13:41:05.190+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: DD.convertCSVtoJSON scheduled__2024-09-28T13:35:33.492527+00:00 [queued]>
[2024-09-28T13:41:05.202+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: DD.convertCSVtoJSON scheduled__2024-09-28T13:35:33.492527+00:00 [queued]>
[2024-09-28T13:41:05.203+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-28T13:41:05.203+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-09-28T13:41:05.203+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-28T13:41:05.240+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): convertCSVtoJSON> on 2024-09-28 13:35:33.492527+00:00
[2024-09-28T13:41:05.246+0000] {standard_task_runner.py:55} INFO - Started process 3086 to run task
[2024-09-28T13:41:05.250+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'DD', 'convertCSVtoJSON', 'scheduled__2024-09-28T13:35:33.492527+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/1.py', '--cfg-path', '/tmp/tmpqz5rzyo0']
[2024-09-28T13:41:05.252+0000] {standard_task_runner.py:83} INFO - Job 193: Subtask convertCSVtoJSON
[2024-09-28T13:41:05.439+0000] {task_command.py:389} INFO - Running <TaskInstance: DD.convertCSVtoJSON scheduled__2024-09-28T13:35:33.492527+00:00 [running]> on host a613a4933f38
[2024-09-28T13:41:05.535+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=paulcrickard
AIRFLOW_CTX_DAG_ID=DD
AIRFLOW_CTX_TASK_ID=convertCSVtoJSON
AIRFLOW_CTX_EXECUTION_DATE=2024-09-28T13:35:33.492527+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-28T13:35:33.492527+00:00
[2024-09-28T13:41:05.537+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/1.py", line 10, in CSVTOJson
    df = pd.read_csv('data.CSV')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'data.CSV'
[2024-09-28T13:41:05.549+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=DD, task_id=convertCSVtoJSON, execution_date=20240928T133533, start_date=20240928T134105, end_date=20240928T134105
[2024-09-28T13:41:05.551+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2024-09-28T13:41:05.561+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 3086. PIDs of all processes in the group: [3086]
[2024-09-28T13:41:05.580+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 3086
[2024-09-28T13:41:05.591+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-28T13:41:05.608+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 193 for task convertCSVtoJSON (Task received SIGTERM signal; 3086)
[2024-09-28T13:41:05.637+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3086, status='terminated', exitcode=1, started='13:41:04') (3086) terminated with exit code 1
[2024-09-28T13:41:05.638+0000] {local_task_job.py:159} INFO - Task exited with return code 143
[2024-09-28T13:41:05.645+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2024-09-28T13:41:05.645+0000] {local_task_job.py:159} INFO - Task exited with return code 143
