[2024-09-29T19:43:56.441+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: CSVtoJSON.CSVtoJSON manual__2024-09-29T19:43:42.653035+00:00 [queued]>
[2024-09-29T19:43:56.453+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: CSVtoJSON.CSVtoJSON manual__2024-09-29T19:43:42.653035+00:00 [queued]>
[2024-09-29T19:43:56.453+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-29T19:43:56.454+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-09-29T19:43:56.454+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-29T19:43:56.480+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): CSVtoJSON> on 2024-09-29 19:43:42.653035+00:00
[2024-09-29T19:43:56.484+0000] {standard_task_runner.py:55} INFO - Started process 4079 to run task
[2024-09-29T19:43:56.487+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'CSVtoJSON', 'CSVtoJSON', 'manual__2024-09-29T19:43:42.653035+00:00', '--job-id', '442', '--raw', '--subdir', 'DAGS_FOLDER/practice.py', '--cfg-path', '/tmp/tmprgukdddd']
[2024-09-29T19:43:56.488+0000] {standard_task_runner.py:83} INFO - Job 442: Subtask CSVtoJSON
[2024-09-29T19:43:56.661+0000] {task_command.py:389} INFO - Running <TaskInstance: CSVtoJSON.CSVtoJSON manual__2024-09-29T19:43:42.653035+00:00 [running]> on host a8bd47e3eb35
[2024-09-29T19:43:56.761+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=CSVtoJSON
AIRFLOW_CTX_TASK_ID=CSVtoJSON
AIRFLOW_CTX_EXECUTION_DATE=2024-09-29T19:43:42.653035+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-29T19:43:42.653035+00:00
[2024-09-29T19:43:56.762+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/practice.py", line 8, in CSVtoJson
    df = pd.read_csv("data.CSV")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'data.CSV'
[2024-09-29T19:43:56.774+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=CSVtoJSON, task_id=CSVtoJSON, execution_date=20240929T194342, start_date=20240929T194356, end_date=20240929T194356
[2024-09-29T19:43:56.799+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 442 for task CSVtoJSON ([Errno 2] No such file or directory: 'data.CSV'; 4079)
[2024-09-29T19:43:56.820+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-29T19:43:56.842+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
